### ISSUE TITLE
ACL with CIDR for olap

### ISSUE THREAD

**Issue by wjy1100** [danieldin95/openlan#43]
ACL with CIDR for olap

**Comment by danieldin95** [comment]
please describe your issue as much detail as possible

**Comment by wjy1100** [comment]
Using ACL to control the destination IP access of the host

**Comment by danieldin95** [comment]
你的意思是你需要通过ACL控制OLAP访问的目的地址或者TCP/UDP端口？用来限制OLAP对局域网内的其他的访问，达到保护局域网络的目的？

**Comment by danieldin95** [comment]
目前OLSW支持OpenVPN的接入，不知你是否使用？是否涉及对于OpenVPN的接入控制？

**Comment by danieldin95** [comment]
> 你的意思是你需要通过ACL控制OLAP访问的目的地址或者TCP/UDP端口？用来限制OLAP对局域网内的其他的访问，达到保护局域网络的目的？

**Comment by danieldin95** [comment]
你可以临时使用ebtables或者iptables来实现接入控制，当前openlan还是聚焦在vpn配置。

**Comment by danieldin95** [comment]
you call configure acl in file `/etc/openlan/switch/acl/acl-1.json`:
{
  "name": "acl-1",
  "rules": [
    {
      "dest": "192.168.77.121",
      "proto": "tcp",
      "dstPort": 443,
      "action": "drop"
    },
    {
      "dest": "192.168.10.0/24",
      "action": "drop"
    }
  ]
}
and enable acl-1 for network `hi` in file `/etc/openlan/switch/network/hi.json`:

{
  "name": "hi",
  "acl": "acl-1"
}

**Comment by wjy1100** [comment]
good!
