### ISSUE TITLE
Support fixed IP for vpn clients

### ISSUE THREAD

**Issue by sunbinnnnn** [danieldin95/openlan#81]
I think fixed IP for client-2-client(server actually) communication is necessary.

**Comment by sunbinnnnn** [comment]
@danieldin95

**Comment by danieldin95** [comment]
add ccd directory in openvpn's server configuration:
``` 
client-config-dir ccd
```
and write client's options in ccd/\<name\> file:
```
ifconfig-push 10.8.0.50 10.8.0.49
```
